apiVersion: integration/v1
kind: Trigger
name: gitlab-trigger-merge-request-merged
version: 1
summary: Gitlab merge request merged

description: |
  This trigger fires when a Gitlab merge request is merged.

responders:
- webhook

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/gitlab-trigger-pull-request-merged

examples:
- summary: When a merge request is merged
  content:
    apiVersion: v1
    kind: Trigger
    name: gitlab-merge-request-merged
    source:
      type: webhook
      image: relaysh/gitlab-trigger-merge-request-merged
    binding:
      parameters:
        repository: !Data repository
        branch: !Data branch
