apiVersion: integration/v1
kind: Trigger
name: github-trigger-pull-request-merged
version: 1
summary: GitHub pull request merged

description: |
  This trigger fires when a GitHub pull request is merged.

responders:
- webhook

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#

build:
  apiVersion: build/v1
  kind: Docker
