apiVersion: integration/v1
kind: Trigger
name: gitlab-trigger-merge-request-opened
version: 1
summary: Gitlab merge request opened

description: |
  This trigger fires when a Gitlab merge request is opened.

responders:
- webhook

schemas:
  event:
    source: file
    file: event.schema.json

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/gitlab-trigger-pull-request-opened

examples:
- summary: When a merge request is opened
  content:
    apiVersion: v1
    kind: Trigger
    name: gitlab-merge-request-opened
    source:
      type: webhook
      image: relaysh/gitlab-trigger-merge-request-opened
    binding:
      parameters:
        repository: !Data repository
        branch: !Data branch
