apiVersion: integration/v1
kind: Trigger
name: gitlab-trigger-merge-request-opened
version: 1
summary: Gitlab merge request opened

description: |
  This trigger fires when a Gitlab merge request is opened.

responders:
- webhook

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/gitlab-trigger-pull-request-opened
